//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DbgRemote.rc
//
#define ID_TRACVWPOP_FIND               0
#define IDD_ABOUTBOX                    100
#define IDD_DBGREMOTE_FORM              101
#define IDD_APPOPTIONS_MAIN_PG          107
#define IDR_MAINFRAME                   128
#define IDR_DBGREMTYPE                  129
#define IDD_CONNECTOPTS_DLG             130
#define IDI_ICON1                       134
#define IDR_TOOLBAR_DBG                 137
#define IDR_TRACEVW_POPUP               137
#define IDR_TOOLBAR_EDIT                139
#define IDD_TEXTFIND_DLG                141
#define IDD_RUNOPTIONS_DLG              142
#define IDR_FINDPOPUP                   143
#define IDD_FILEFIND_DLG                144
#define IDD_GOTO_DLG                    145
#define IDI_ICON2                       146
#define IDD_EXPRDISPLAY_DLG             148
#define IDD_EDITBREAKPT_DLG             149
#define IDD_REGISTRYOPTS_PG             150
#define IDD_EDITOROPTS_PG               151
#define IDD_PROJECTSETTINGS_DLG         152
#define IDD_FILEPROP_DLG                153
#define IDB_FILEIMAGELIST_BMP           154
#define IDR_FILEPOPUP                   155
#define IDD_FILE_GROUP_DLG              157
#define IDD_GRPPROP_DLG                 158
#define IDD_TEXTREPLACE_DLG             160
#define IDD_DOCSEL_DLG                  162
#define IDD_CONFIGTOOL_DLG              163
#define IDD_DEBUGOPTIONS_PG             164
#define IDD_FILEMODIFIED_DLG            165
#define IDD_FINDINPROJECT_DLG           166
#define ID_EDIT_GOTOTAGDEFINITION       167
#define IDD_BROWSESEL_DLG               168
#define ID_PROJECT_BUILDTAGS            169
#define IDR_HAPPROJTYPE                 170
#define ID_                             172
#define ID_TRACVWPOP_CLEARONRUN         173
#define ID_TRACVWPOP_CLEARRUN           173
#define ID__CUT                         174
#define ID__PASTE                       175
#define ID__COPY177                     177
#define ID_ED                           178
#define ID__CUT179                      179
#define ID_TRACVWPOP_CLEARALL           180
#define ID__CLEARONRUN                  181
#define ID__FINDNEXT                    182
#define IDR_EDITVW_POPUP                183
#define ID_VIEW_SPLITWINDOW             184
#define IDC_LOCAL_RDO                   1000
#define IDC_REMOTE_RDO                  1001
#define IDC_REMOTENAME_CBO              1003
#define IDC_REMOTENAME_STC              1004
#define IDC_EDIT1                       1006
#define IDC_RUNSCRIPT_EDT               1006
#define IDC_LINENUM_EDT                 1006
#define IDC_EXPR_EDT                    1006
#define IDC_TABWIDTH_EDT                1006
#define IDC_PROJECTNAME_EDT             1006
#define IDC_FILENAME_EDT                1006
#define IDC_FILE_GROUP_EDIT             1006
#define IDC_GROUPNAME_EDT               1006
#define IDC_PYTHONHELP_EDT              1006
#define IDC_NAME_EDT                    1006
#define IDC_FINDTXT_CBO                 1007
#define IDC_RUNSCRIPT_EDT2              1007
#define IDC_REGEX_BTN                   1008
#define IDC_MATCHWORD_CHK               1009
#define IDC_MATCHSTART_CHK              1010
#define IDC_MATCHCASE_CHK               1011
#define IDC_REGEXP_CHK                  1012
#define IDC_FOLDERBROWSE_BTN            1013
#define IDC_RUNPARAM_EDT                1014
#define IDC_WORKDIR_EDT                 1015
#define IDC_WORKDIRBROWSE_BTN           1016
#define IDC_SCRIPTBROWSE_BTN            1017
#define IDC_FILETYPE_CBO                1017
#define IDC_FOLDER_CBO                  1018
#define IDC_RESULTS_LST                 1019
#define IDC_SETDBGSCRIPT_BTN            1020
#define IDC_DEBUGNM_STC                 1021
#define IDC_VALUE_EDT                   1022
#define IDC_BUILDTIME_STC               1025
#define IDC_COPYWRITE_STC               1026
#define IDC_BREAKPT_LCTRL               1028
#define IDC_PYTHONVER_STC               1029
#define IDC_PYTHONCOPY_STC              1030
#define IDC_VERSION_STC                 1031
#define IDC_PYTHONBUILD_STC             1032
#define IDC_OPENWITH_BTN                1038
#define IDC_SETEDITOR_BTN               1039
#define IDC_PYFILE_GRP                  1040
#define IDC_STYLE_LST                   1042
#define IDC_FORECOL_BTN                 1047
#define IDC_FONTSEL_BTN                 1048
#define IDC_BACKCOL_BTN                 1049
#define IDC_RESTORECUR_BTN              1050
#define IDC_RESTOREALL_BTN              1051
#define IDC_CARETCOL_BTN                1052
#define IDC_FULLPATH_EDT                1053
#define IDC_MODIFIED_EDT                1054
#define IDC_FILESTATUS_EDT              1055
#define IDC_AUTOOPENPROJ_CHK            1056
#define IDC_FILE_GROUP_LBL              1059
#define IDC_GROUPFILE_LST               1060
#define IDC_GROUP_CBO                   1061
#define IDC_FOLDOPEN_CHK                1062
#define IDC_REPLACEWHAT_CBO             1064
#define IDC_REPLACEWITH_CBO             1065
#define IDC_REPLACESEL_RDO              1068
#define IDC_REPWHOLE_RDO                1069
#define IDC_FINDNEXT_BTN                1070
#define IDC_REPLACE_BTN                 1071
#define IDC_REPLACEALL_BTN              1072
#define IDC_REPLACEIN_GRP               1073
#define IDC_REPLACEWITH_STC             1074
#define IDC_ADVDEBUG_CHK                1077
#define IDC_BROWSEDIR_BTN               1081
#define IDC_REMPATH_EDT                 1082
#define IDC_DOCLIST_TRE                 1085
#define IDC_TOOLS_LST                   1086
#define IDC_CMD_EDT                     1087
#define IDC_DIR_EDT                     1088
#define IDC_PARAM_EDT                   1089
#define IDC_BROWSECMD_BTN               1090
#define IDC_ADD_BTN                     1092
#define IDC_REMOVE_BTN                  1093
#define IDC_XMLEXTERN_CHK               1095
#define IDC_BREAKFIRSTLINE_CHK          1096
#define IDC_BREAKEXCEP_CHK              1097
#define IDC_AUTOWATCHPOP_CHK            1101
#define IDC_HELPBROWSE_BTN              1102
#define IDC_CURLANG_CBO                 1103
#define IDC_FILENM_STC                  1104
#define IDC_BREAKALWAYS_RDO             1105
#define IDC_BRAKUNHANDLED_RDO           1106
#define IDC_IGNOREEXCEP_RDO             1107
#define IDC_STATIC_NUMRESULTS           1108
#define IDC_BROWSE_CLTL                 1111
#define IDC_CHECK1                      1112
#define IDC_CLEAROUT_CHK                1112
#define IDC_USETABS_CHK                 1113
#define ID_DEBUG_CONNECT                32771
#define ID_DEBUG_EXECUTE                32772
#define ID_DEBUG_GO                     32773
#define ID_VIEW_CALLSTACK               32774
#define ID_VIEW_WATCH                   32775
#define ID_VIEW_DEBUGOUTPUT             32776
#define ID_VIEW_LOCALS                  32777
#define ID_DEBUG_BREAKNOW               32779
#define ID_DEBUG_STOPDEBUGGING          32780
#define ID_VIEW_PROJECT                 32781
#define ID_DEBUG_RUNDEBUGGER            32782
#define ID_DEBUG_STEPIN                 32783
#define ID_DEBUG_STEPOUT                32784
#define ID_DEBUG_STEPOVER               32785
#define ID_DEBUG_BREAKPOINTS_TOGGLE     32786
#define ID_DEBUG_BREAKPOINTS_CLEARALL   32787
#define ID_BOOKMARKS_TOGGLE             32788
#define ID_BOOKMARKS_GOTONEXT           32789
#define ID_BOOKMARKS_GOTOPREVIOUS       32790
#define ID_BOOKMARKS_CLEARALL           32791
#define ID_EDIT_FINDINFILES             32815
#define ID_VIEW_EDITOROPTIONS_VIEWWHITESPACE 32816
#define ID_VIEW_SELECTIVEDISPLAY        32818
#define ID_VIEW_LINENUMBERS             32819
#define ID_DEBUG_RUNOPTIONS             32820
#define ID_FINDPOP_ANYCHAR              32821
#define ID_FINDPOP_CHARINSET            32822
#define ID_FINDPOP_CHARNOTINSET         32823
#define ID_FINDPOP_STARTWORD            32824
#define ID_FINDPOP_ENDWORD              32825
#define ID_FINDPOP_STARTOFLINE          32826
#define ID_FINDPOP_ENDOFLINE            32827
#define ID_FINDPOP_ZEROMORE             32828
#define ID_FINDPOP_ONEMORE              32829
#define ID_FINDPOP_TAGPART              32830
#define ID_FINDPOP_TABCHAR              32831
#define ID_EDIT_FINDNEXT                32833
#define ID_EDIT_GOTOLINE                32834
#define ID_VIEW_EDITOROPTIONS_VIEWLINEENDINGS 32835
#define ID_VIEW_VIEWLINEENDINGS         32836
#define ID_DEBUG_ADDTOWATCH             32837
#define ID_FILE_NEWPROJECT              32838
#define ID_FILE_OPENPROJECT             32839
#define ID_DEBUG_TESTCOMPILE            32841
#define ID_DEBUG_BREAKPOINTS_EDITBREAKPOINTS 32845
#define ID_BREAKPOINTS_EDIT             32846
#define ID_HELP_PYTHONHELP              32847
#define ID_FILE_SAVEALL                 32848
#define ID_TOOLS_OPTIONS                32849
#define ID_EDIT_SPACESTOTABS            32850
#define ID_PROJECT_ADDTOPROJECT_FILES   32851
#define ID_PROJECT_SOURCECONTROL_CONFIGURE 32852
#define ID_PROJECT_SETTINGS             32854
#define ID_PROJECT_SOURCECONTROL_CHECKOUT 32855
#define ID_PROJECT_SOURCECONTROL_CHECKIN 32856
#define ID_PROJECT_SOURCECONTROL_UNDOCHECKOUT 32857
#define ID_PROJECT_SOURCECONTROL_ADDTOSOURCECONTROL 32858
#define ID_PROJECT_SOURCECONTROL_REMOVEFROMSOURCECONTROL 32859
#define ID_PROJECT_SOURCECONTROL_REFRESHSTATUS 32860
#define ID_PROJECT_ADDTOPROJECT_DOCUMENTS 32861
#define ID__SETASBOOTFILE               32862
#define ID__CHECKIN                     32863
#define ID__CHECKOUT                    32864
#define ID__UNDOCHECKOUT                32865
#define ID__PROPERTIES                  32866
#define ID_FILEPOPUP_SETASBOOTFILE      32867
#define ID_FILEPOPUP_CHECKIN            32868
#define ID_FILEPOPUP_CHECKOUT           32869
#define ID_FILEPOPUP_UNDOCHECKOUT       32870
#define ID_FILE_PROPERTIES              32871
#define ID__ADDTOSOURCECONTROL          32872
#define ID__REMOVEFROMSOURCECONTROL     32874
#define ID_FILEPOPUP_ADDTOVCS           32877
#define ID_FILE_MRU_PROJECT1            32878
#define ID_FILE_MRU_PROJECT2            32879
#define ID_FILE_MRU_PROJECT3            32880
#define ID_FILE_MRU_PROJECT4            32881
#define ID_FILE_MRU_PROJECT5            32882
#define ID_FILE_MRU_PROJECT6            32883
#define ID_FILE_MRU_PROJECT7            32884
#define ID_FILE_MRU_PROJECT8            32885
#define ID_FILE_MRU_PROJECT9            32886
#define ID_FILEPOPUP_GROUP              32887
#define ID_FILEPOPUP_EXPLORER           32888
#define ID_FILEPOPUP_CMDPROMPT          32889
#define ID_VIEW_ENDOFLINETYPE_CRLF      32891
#define ID_VIEW_ENDOFLINETYPE_CR        32892
#define ID_VIEW_ENDOFLINETYPE_LF        32893
#define ID_WINDOW_CLOSEALL              32894
#define ID_EDIT_COMMENT                 32895
#define ID_EDIT_UNCOMMENT               32896
#define ID_EDIT_UNCOMMENTLINE           32897
#define ID_EDIT_COMMENTLINE             32898
#define ID_TOOLS_PYTHONINTERACTIVE      32899
#define ID_TOOLS_TOOLS_TOOLSMENU1       32903
#define ID_TOOLS_TOOLS_TOOLSMENU2       32904
#define ID_TOOLS_TOOLS_TOOLSMENU3       32905
#define ID_TOOLS_TOOLS_TOOLSMENU4       32906
#define ID_TOOLS_TOOLS_TOOLSMENU5       32907
#define ID_TOOLS_TOOLS_TOOLSMENU6       32908
#define ID_DEBUG_PYTHONVERSION_DEBUG    32909
#define ID_DEBUG_PYTHONVERSION_RELEASE  32910
#define ID_DEBUG_PYVER_DEBUG            32911
#define ID_DEBUG_PYVER_REL              32912
#define ID_FILE_CLOSEPROJECT            32913
#define ID_TOOLS_TOOLS_CONFIGURE        32916
#define ID__REMOVEFROMPROJECT           32917
#define ID_FILEPOPUP_REMOVEFROMPROJECT  32918
#define ID__DIFFFILE                    32919
#define ID__SYNCFILE                    32920
#define ID_FILEPOPUP_SYNCFILE           32921
#define ID_FILEPOPUP_DIFFFILE           32922
#define ID__FINDINPROJECT               32923
#define ID_FILEPOPUP_FINDINPROJECT      32924
#define ID_VIEW_EDITOROPTIONS_COLLAPSEALL 32925
#define ID_VIEW_COLLAPSEALL             32926
#define ID_VIEW_EDITOROPTIONS_EXPANDALL 32927
#define ID_VIEW_EXPANDALL               32928
#define ID_FILEPOPUP_PROPERTIES			32929
#define ID_INDICATOR_READ               59142
#define ID_INDICATOR_LINE               59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32930
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
