//////////////////////////////////////////////////////////////////////////////
//  File:    Tags.h
//
//  Purpose: This file defines a class which manages data generated by the 
//  ctags.exe program.  The ctags program can be found at:
//  http://sourceforge.net/projects/ctags
//
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
//  Copyright (C) 2001 by Humongous Entertainment
//  
//  This library is free software; you can redistribute it and/or modify it 
//  under the terms of the GNU Lesser General Public License as published by 
//  the Free Software Foundation; either version 2.1 of the License, or  any 
//  later version.
//  
//  This library is distributed in the hope that it will be useful, but 
//  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
//  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public 
//  License for more details.
//  
//  You should have received a copy of the GNU Lesser General Public License 
//  along with this library (see the file license.txt); if not, write to the 
//  Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//////////////////////////////////////////////////////////////////////////////	
#pragma once
#include <map>
#include <vector>

class CTags
{
public:
	CTags();
	~CTags();

	bool LoadTagsFile(const char* cszTagsFile);
	bool FindTagInfo(const char* cszTag, vector<string>& files, vector<int>& lines)const;
	bool HasData()const;
	void ClearTagInfo();
	bool BuildTagsFile(const char* cszTagFile, const char* cszPaths);


private:
	//the tag file we're using
	string m_tagFile;
};
